id = "bend"
name = "Bend"
description = "Bend 2 syntax highlighting."
version = "0.1.0"
schema_version = 1
authors = ["Christian Bager Bach Houmann <christian@bagerbach.com>"]
repository = "https://github.com/chhoumann/zed-bend"

[grammars.bend]
repository = "https://github.com/chhoumann/zed-bend"
rev = "4893f6e52ba9b06a486a93781805beccf5a24d0d"
